[package]
name = "oxfs"
version.workspace = true
edition.workspace = true

[[bin]]
name = "oxfs"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive", "env"] }
oxfs-flat = { workspace = true }
oxfs-posix = { workspace = true }
oxfs-backend = { workspace = true }
fuser = "0.17"
daemonize = "0.5"
