[package]
name = "oxfs-vfs"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
oxfs-meta = { workspace = true }
oxfs-data = { workspace = true }
moka = { version = "0.12", features = ["future"] }
parking_lot = "0.12"
futures = "0.3"
