[package]
name = "oxfs-fuse"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
fuser = "0.17"
oxfs-vfs = { workspace = true }
oxfs-meta = { workspace = true }
libc = "0.2"
